<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerInmjvrf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerInmjvrf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerInmjvrf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerInmjvrf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerInmjvrf\appDevDebugProjectContainer();
